#make in folder to create program
#This is simple, i dont understand g++ and everything else .-.
output: AV.o
	g++ AV.o -o dv1620program

AV.o: AV.cpp
	g++ -c AV.cpp

target: dependencies
	action

clean:
	rm *.o dv1620program